### ISSUE TITLE
Helm chart repository broken?

### ISSUE THREAD

**Issue by alexkuretz** [pelotech/nidhogg#42]
Apologies if I'm missing something, but I'm not able to pull your helm chart.

```
$ helm repo add nidhogg https://ghcr.io/pelotech/charts/nidhogg
Error: looks like "https://ghcr.io/pelotech/charts/nidhogg" is not a valid chart repository or cannot be reached: failed to fetch https://ghcr.io/pelotech/charts/nidhogg/index.yaml : 404 Not Found

$ helm repo add nidhogg https://ghcr.io/pelotech/charts/
Error: looks like "https://ghcr.io/pelotech/charts/" is not a valid chart repository or cannot be reached: failed to fetch https://ghcr.io/pelotech/charts/index.yaml : 404 Not Found
```

**Comment by scoquelin** [comment]
Hi,

Thanks for reporting, however `helm repo` subcommands are not supported for OCI registries. 😞 

`helm pull oci://ghcr.io/pelotech/charts/nidhogg` should allow you to download the chart

**Comment by alexkuretz** [comment]
Thanks, I missed it was an OCI registry. I was actually trying to install with the helm_release terraform provider and fell back to testing with Helm to verify I wasn't making a mistake. I ended up manually installing by downloading the chart.

It looks like only the 0.1.0 chart is available, is that intentional? I was expecting the 0.5.3 chart.

``` Error: ghcr.io/pelotech/charts/nidhogg:0.5.3: not found```

This works:
```
resource "helm_release" "nidhogg" {
  name             = "nidhogg"
  repository       = "oci://ghcr.io/pelotech/charts"
  chart            = "nidhogg"
  version          = "0.1.0"
  namespace        = "nidhogg"
  create_namespace = true
```

This does not:
```
resource "helm_release" "nidhogg" {
  name             = "nidhogg"
  repository       = "oci://ghcr.io/pelotech/charts"
  chart            = "nidhogg"
  version          = "0.5.3"
  namespace        = "nidhogg"
  create_namespace = true
```

**Comment by scoquelin** [comment]
Yes, only the `0.1.0` is available for now. We have some ongoing work to do to be able to publish latest version.
